version: '2'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/:/etc/nginx/conf/
    ports:
      - "80:80"
      - "443:443"
    links:
      - blog
      - sinopia
      - hhfanyi_mobile
      - hhfanyi_api

  blog:
    build: ./hexo
    restart: always
    volumes:
      - ~/blog/:/app/
    expose:
      - 4000

  sinopia:
    image: keyvanfatehi/sinopia
    restart: always
    volumes:
      - ./npm-registry/sinopia/config.yaml:/opt/sinopia/config.yaml
      - ./npm-registry/sinopia/htpasswd:/opt/sinopia/htpasswd
      - ./npm-registry/sinopia/storage/:/opt/sinopia/storage/
    expose:
      - 4873

  mongo:
    image: mongo
    restart: always
    volumes:
      - ~/data/:/data/db/
    expose:
      - 27017

  hhfanyi_mobile:
    image: node:8.10.0
    restart: always
    volumes:
      - ~/hhfanyi/nicemall-mobile/:/app/
    working_dir: /app/
    environment:
      API_SERVICE_URL: 'http://hhfanyi_api:7001'
    command: "npm run build-start"
    expose:
      - 3000

  hhfanyi_api:
    image: node:8.10.0
    restart: always
    volumes:
      - ~/hhfanyi/nicemall-api/:/app/
    working_dir: /app/
    environment:
      DB_URL: 'mongodb://mongo/nicemall'
    command: npm run start
    expose:
      - 7001
