version: '2'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/:/etc/nginx/conf/
    ports:
      - "80:80"
      - "443:443"
    links:
      - blog
      - sinopia

  blog:
    build: ./jekyll
    restart: always
    volumes:
      - ~/liangxiaojie.github.io/:/srv/jekyll/
    expose:
      - 4000

  sinopia:
    image: keyvanfatehi/sinopia
    restart: always
    volumes:
      - ./npm-registry/sinopia/config.yaml:/opt/sinopia/config.yaml
      - ./npm-registry/sinopia/htpasswd:/opt/sinopia/htpasswd
      - ./npm-registry/sinopia/storage/:/opt/sinopia/storage/
    expose:
      - 4873
