version: '2'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/:/etc/nginx/conf/
    ports:
      - "80:80"
      - "443:443"
    links:
      - blog

  blog:
    build: ./jekyll
    restart: always
    volumes:
      - ~/liangxiaojie.github.io/:/srv/jekyll/
    expose:
      - 4000
